config/routes.rb
Rails.application.routes.draw do
  

  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'
  get '/conntact', to: 'static_pages#conntact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  

  resources :users do
      member do
        get :followers
        get :following
      end
    end
    resources :account_activations, only: [:edit]
    resources :passwords, except: [:destroy]
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  	before_save { email.downcase! }
	validates :name, presence: true, length:{maximum:50}
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length:{maximum:255} ,format:{ with:VALID_EMAIL_REGEX},uniqueness: { case_sensitive: false}
	has_secure_password
	validates :password,presence: true,length:{maximum:6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
  	render html: "Hello World!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        if user.activated
          log_in user
          params[:session][:remember_me] == '1' ? remember(user) : forget(user)
          redirect_back_or user
        else
          message = "Account not activated, check your email for the activation link"
          flash[:warning] = message
          redirect_to root_url
        end
      else
        flash.now[:danger] = '邮箱或者密码错误'
        render 'new'
      end
    end

    def destroy
      log_out if logged_in?
      redirect_to root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  	
  end

  def conntact
  	render :json => {
     :name=>"xiaoliang",
     :adress=>"上海市南翔镇",
     :sex=>"男"
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user=User.new
  end
  def show
  	  @user = User.find(params[:id])
  	  # debugger  #调试代码用的东西
  end
  def create
  	@user = User.new(user_params)
    if @user.save
      # 处理注册成功的情况
        flash[:success] = "Welcome to the Sample App!"
        redirect_to user_url(@user)
    else
      render 'new'
    end

  end
  def user_params
  	params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# 根据所在的页面返回完整的标题
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# def gratavar_for(user,size)
	# 	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	# 	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	# 	image_tag(gravatar_url, alt: user.name, class: "gravatar",size: size)
	# end

	 # 返回指定用户的 Gravatar
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">BinKingLiang</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于",about_path %></li>
      <li><%= link_to "联系我们", conntact_path %></li>
      <li><a href="http://news.railstutorial.org/">新闻</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "简单的登录注册", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "主页",   root_path %></li>
        <li><%= link_to "帮助",   help_path %></li>
        <li><%= link_to "登录", login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<title><%= full_title(yield(:title)) %></title>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/conntact.html.erb
<% provide(:title,"Contact") %>
<h1>Contact</h1>
<p>
  关于简单的登录界面，可以联系学习的网站.
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<title><%= full_title(yield(:title)) %></title>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>欢迎来到我的世界</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "现在注册", new_user_path, class: "btn btn-lg btn-primary" %>
</div>

<!-- <%= link_to image_tag("IMG_3417.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %> -->

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>注册</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: users_path) do |f| %>

      <%= render 'shared/error_messages'%>

      <%= f.label :name,'用户名' %>
      <%= f.text_field :name ,class: 'from-control'%>

      <%= f.label :email,'邮箱' %>
      <%= f.email_field :email, class: 'from-control' %>

      <%= f.label :password ,'密码'%>
      <%= f.password_field :password ,class: 'from-control' %>

      <%= f.label :password_confirmation, "确认密码" %>
      <%= f.password_field :password_confirmation,class: 'from-control' %>

      <%= f.submit "注册", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:name,@user.name) %>

<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for(@user,{size: 100}) %>
				<%= @user.email %>
			</h1>
		</section>
	</aside>
</div>